.PHONY: all clean

all:
	$(MAKE) -C libinotify
	$(MAKE) -C libmincrypt
	$(MAKE) -C libsepol
	$(MAKE) -C libsparse
	$(MAKE) -C zlib

clean:
	$(MAKE) -C libinotify clean
	$(MAKE) -C libmincrypt clean
	$(MAKE) -C libsepol clean
	$(MAKE) -C libsparse clean
	$(MAKE) -C zlib clean
